/* eslint-disable import/prefer-default-export */
export const SET_APP_CREATED = 'SET_APP_CREATED';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_AUTH_TOKEN_REFRESHING = 'SET_AUTH_TOKEN_REFRESHING';
export const SET_AUTH_PROCESS_COMPLETED = 'SET_AUTH_PROCESS_COMPLETED';
export const SET_USER = 'SET_USER';
export const SET_LOADING = 'SET_LOADING';
export const SET_INITIAL_LOADING = 'SET_INITIAL_LOADING';
export const SET_MENU_BADGES = 'SET_MENU_BADGES';
export const SET_SNACKBAR = 'SET_SNACKBAR';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_ALERT_COMPONENT = 'SET_ALERT_COMPONENT';
export const CLEAR_ALERT_COMPONENT = 'CLEAR_ALERT_COMPONENT';

